# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-gi0EBL9DttJ3tb0VndgDcLp5cfrkQq

##**Import Library & Konfigurasi Path**
"""

import mlflow
import mlflow.sklearn
import pandas as pd
import pickle
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

TRAIN_DATA_PATH = "sleep_health_preprocessing/train.pkl"
TEST_DATA_PATH = "sleep_health_preprocessing/test.pkl"


# Nama Experiment di MLflow
EXPERIMENT_NAME = "Sleep_Health_Experiment_Asyifa"

"""##**Fungsi Load Data**"""

def load_data(path):
    """Memuat data pickle (X, y)."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"File {path} tidak ditemukan. Pastikan automate_asyifa.py sudah dijalankan!")

    with open(path, 'rb') as f:
        data = pickle.load(f)
    return data

"""##**Fungsi Evaluasi Metrik**"""

def eval_metrics(actual, pred):
    """Menghitung metrik evaluasi klasifikasi."""
    accuracy = accuracy_score(actual, pred)
    # Gunakan average='weighted' karena ini klasifikasi multiclass
    precision = precision_score(actual, pred, average='weighted', zero_division=0)
    recall = recall_score(actual, pred, average='weighted', zero_division=0)
    f1 = f1_score(actual, pred, average='weighted', zero_division=0)
    return accuracy, precision, recall, f1

"""##**Fungsi Utama (Training & Logging)**"""

def train_model():
    # 1. Setup MLflow Experiment
    mlflow.set_experiment(EXPERIMENT_NAME)

    # 2. Load Data
    print("Loading data...")
    try:
        X_train, y_train = load_data(TRAIN_DATA_PATH)
        X_test, y_test = load_data(TEST_DATA_PATH)
    except Exception as e:
        print(f"Error loading data: {e}")
        return

    # 3. Definisi Hyperparameter
    n_estimators = 100
    max_depth = 10
    random_state = 42

    print("Starting training...")

    # --- MULAI MLFLOW RUN ---
    # Kita menggunakan 'with mlflow.start_run()' agar run otomatis ditutup setelah selesai
    with mlflow.start_run(run_name="Baseline_RF"):
        # A. Inisialisasi Model
        rf = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            random_state=random_state
        )

        # B. Training Model
        rf.fit(X_train, y_train)

        # C. Prediksi
        y_pred = rf.predict(X_test)

        # D. Evaluasi
        acc, prec, rec, f1 = eval_metrics(y_test, y_pred)

        print(f"  Accuracy: {acc:.4f}")
        print(f"  F1 Score: {f1:.4f}")

        # E. LOGGING KE MLFLOW (Syarat Kriteria 2)
        # 1. Log Parameter (Settingan model)
        mlflow.log_param("n_estimators", n_estimators)
        mlflow.log_param("max_depth", max_depth)
        mlflow.log_param("model_type", "RandomForestClassifier")

        # 2. Log Metrics (Hasil performa)
        mlflow.log_metric("accuracy", acc)
        mlflow.log_metric("precision", prec)
        mlflow.log_metric("recall", rec)
        mlflow.log_metric("f1_score", f1)

        # 3. Log Model (Simpan model agar bisa dipakai nanti/serving)
        mlflow.sklearn.log_model(rf, "model")

        print(f"Run ID: {mlflow.active_run().info.run_id}")
        print("Model logged to MLflow successfully!")

# Jalankan fungsi training
if __name__ == "__main__":
    train_model()